#ifndef bitmap_h
#define bitmap_h

#include <stdint.h>

enum image_encoding { image_encoding_1bit, image_encoding_565bits };

struct external_flash_data;

// Bitmap stored in the internal flash.

struct bitmap {
    const uint8_t *image;
    uint32_t width;
    uint32_t height;
    enum image_encoding encoding;
};

// Bitmap stored in the external flash.

struct bitmap_ext {
    // This points to an instance of the external_flash_data structure
    // generated by the pack-flash.py script.
    const struct external_flash_data *flash_data;
    uint32_t width;
    uint32_t height;
    enum image_encoding encoding;
};

#endif // bitmap_h
