#include <device/nrf51822_peripherals.h>

#define SPIS_ENABLED 1
#define SPI0_ENABLED 1
#define SPI1_ENABLED 0
#define SPI2_ENABLED 0
#define SPIS0_ENABLED 0
#define SPIS1_ENABLED 1
#define SPIS2_ENABLED 0
#define APP_SCHEDULER_ENABLED 1
#define APP_TIMER_ENABLED 1
#define APP_GPIOTE_ENABLED 1
#define GPIOTE_ENABLED 1
#define GPIOTE_CONFIG_IRQ_PRIORITY 3
#define GPIOTE_CONFIG_NUM_OF_LOW_POWER_EVENTS 4
#define BLE_DIS_ENABLED 1
